### ISSUE TITLE
Python 3 long is not defined

### ISSUE THREAD

**Issue by jrrios** [NVIDIA-AI-IOT/argus_camera#1]
Hello, I tried installing the library but I am facing this issue, I found that `long` has been removed in python3

I am using a Jetson TX2 and python3 for development, here is the error I am getting

Traceback (most recent call last):
  File "infer.py", line 7, in <module>
    from argus_camera import ArgusCamera
  File "/usr/local/lib/python3.5/dist-packages/argus_camera-0.0-py3.5-linux-aarch64.egg/argus_camera/__init__.py", line 1, in <module>
    from .argus_camera import ArgusCamera
  File "/usr/local/lib/python3.5/dist-packages/argus_camera-0.0-py3.5-linux-aarch64.egg/argus_camera/argus_camera.py", line 4, in <module>
    class ArgusCamera:
  File "/usr/local/lib/python3.5/dist-packages/argus_camera-0.0-py3.5-linux-aarch64.egg/argus_camera/argus_camera.py", line 10, in ArgusCamera
    frame_duration_range=(long(1e9//30), long(1e9//30)),
NameError: name 'long' is not defined

Thank you

**Comment by LMSAas** [comment]
This can be solved by adding to argus_camera.py:

`from past.builtins import long`

and

`pip3 install futures`
